### PR TITLE
Document need to include `requirements.txt` file

### PR DESCRIPTION
**Pull request by der-gabe**
…  in the updated flask+redis example.

### CODE REVIEW

**Review by agracey — APPROVED** [review]
Added simple change to work with parser. Thank you so much for the help!

**Comment by der-gabe** [comment]
Oh right, the formatting... yeah, I wasn't sure what it should be and thought it'd work without.

Thanks for the fix!

**Comment by agracey** [comment]
fixes #105

**Review by timirnich — APPROVED** [review]
Thanks @der-gabe, good addition! I'll go ahead and merge this.

**Pull request merged**
